// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/logic/captioning/captioning_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:flutter_bloc/flutter_bloc.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yofardev_captioner/logic/images_list/image_list_cubit.dart'
    as _i2;
import 'package:yofardev_captioner/models/app_image.dart' as _i3;
import 'package:yofardev_captioner/models/llm_config.dart' as _i7;
import 'package:yofardev_captioner/repositories/captioning_repository.dart'
    as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageListState_0 extends _i1.SmartFake
    implements _i2.ImageListState {
  _FakeImageListState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAppImage_1 extends _i1.SmartFake implements _i3.AppImage {
  _FakeAppImage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImageListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageListCubit extends _i1.Mock implements _i2.ImageListCubit {
  MockImageListCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.ImageListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeImageListState_0(this, Invocation.getter(#state)),
          )
          as _i2.ImageListState);

  @override
  _i4.Stream<_i2.ImageListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i4.Stream<_i2.ImageListState>.empty(),
          )
          as _i4.Stream<_i2.ImageListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  void onInit() => super.noSuchMethod(
    Invocation.method(#onInit, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> onFolderPicked(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#onFolderPicked, [folderPath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> onFileOpened(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#onFileOpened, [filePath]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void nextImage() => super.noSuchMethod(
    Invocation.method(#nextImage, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousImage() => super.noSuchMethod(
    Invocation.method(#previousImage, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> saveChanges() =>
      (super.noSuchMethod(
            Invocation.method(#saveChanges, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void onSortChanged(_i2.SortBy? sortBy, bool? sortAscending) =>
      super.noSuchMethod(
        Invocation.method(#onSortChanged, [sortBy, sortAscending]),
        returnValueForMissingStub: null,
      );

  @override
  void onImageSelected(int? index) => super.noSuchMethod(
    Invocation.method(#onImageSelected, [index]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> getSingleImageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleImageSize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void searchAndReplace(String? search, String? replace) => super.noSuchMethod(
    Invocation.method(#searchAndReplace, [search, replace]),
    returnValueForMissingStub: null,
  );

  @override
  void countOccurrences(String? search) => super.noSuchMethod(
    Invocation.method(#countOccurrences, [search]),
    returnValueForMissingStub: null,
  );

  @override
  void updateCaption({required String? caption}) => super.noSuchMethod(
    Invocation.method(#updateCaption, [], {#caption: caption}),
    returnValueForMissingStub: null,
  );

  @override
  void updateImage({required _i3.AppImage? image}) => super.noSuchMethod(
    Invocation.method(#updateImage, [], {#image: image}),
    returnValueForMissingStub: null,
  );

  @override
  void removeImage(int? index) => super.noSuchMethod(
    Invocation.method(#removeImage, [index]),
    returnValueForMissingStub: null,
  );

  @override
  Map<String, int> getAspectRatioCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAspectRatioCounts, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  void emit(_i2.ImageListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i5.Change<_i2.ImageListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}

/// A class which mocks [CaptioningRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaptioningRepository extends _i1.Mock
    implements _i6.CaptioningRepository {
  MockCaptioningRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i3.AppImage> captionImage(
    _i7.LlmConfig? config,
    _i3.AppImage? image,
    String? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#captionImage, [config, image, prompt]),
            returnValue: _i4.Future<_i3.AppImage>.value(
              _FakeAppImage_1(
                this,
                Invocation.method(#captionImage, [config, image, prompt]),
              ),
            ),
          )
          as _i4.Future<_i3.AppImage>);
}
