// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/features/structured_captioning/logic/structured_captioning_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i10;

import 'package:flutter_bloc/flutter_bloc.dart' as _i7;
import 'package:mockito/mockito.dart' as _i1;
import 'package:yofardev_captioner/features/image_list/data/models/app_image.dart'
    as _i5;
import 'package:yofardev_captioner/features/image_list/logic/image_list_cubit.dart'
    as _i2;
import 'package:yofardev_captioner/features/llm_config/data/models/llm_config.dart'
    as _i9;
import 'package:yofardev_captioner/features/llm_config/data/models/structured_batch_overrides.dart'
    as _i11;
import 'package:yofardev_captioner/features/structured_captioning/data/models/ideogram_caption.dart'
    as _i3;
import 'package:yofardev_captioner/features/structured_captioning/data/models/vlm_analysis.dart'
    as _i4;
import 'package:yofardev_captioner/features/structured_captioning/data/repositories/structured_caption_repository.dart'
    as _i8;
import 'package:yofardev_captioner/features/structured_captioning/data/services/sam_process_service.dart'
    as _i12;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageListState_0 extends _i1.SmartFake
    implements _i2.ImageListState {
  _FakeImageListState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdeogramCaption_1 extends _i1.SmartFake
    implements _i3.IdeogramCaption {
  _FakeIdeogramCaption_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVlmAnalysis_2 extends _i1.SmartFake implements _i4.VlmAnalysis {
  _FakeVlmAnalysis_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImageListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageListCubit extends _i1.Mock implements _i2.ImageListCubit {
  MockImageListCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.AppImage> get filteredImages =>
      (super.noSuchMethod(
            Invocation.getter(#filteredImages),
            returnValue: <_i5.AppImage>[],
          )
          as List<_i5.AppImage>);

  @override
  List<_i5.AppImage> get displayedImages =>
      (super.noSuchMethod(
            Invocation.getter(#displayedImages),
            returnValue: <_i5.AppImage>[],
          )
          as List<_i5.AppImage>);

  @override
  _i2.ImageListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeImageListState_0(this, Invocation.getter(#state)),
          )
          as _i2.ImageListState);

  @override
  _i6.Stream<_i2.ImageListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.ImageListState>.empty(),
          )
          as _i6.Stream<_i2.ImageListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> onInit({String? folderPath}) =>
      (super.noSuchMethod(
            Invocation.method(#onInit, [], {#folderPath: folderPath}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onFolderPicked(String? folderPath, {bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#onFolderPicked, [folderPath], {#force: force}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onFileOpened(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#onFileOpened, [filePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void nextImage() => super.noSuchMethod(
    Invocation.method(#nextImage, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousImage() => super.noSuchMethod(
    Invocation.method(#previousImage, []),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> saveChanges() =>
      (super.noSuchMethod(
            Invocation.method(#saveChanges, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onSortChanged(_i2.SortBy? sortBy, bool? sortAscending) =>
      super.noSuchMethod(
        Invocation.method(#onSortChanged, [sortBy, sortAscending]),
        returnValueForMissingStub: null,
      );

  @override
  void onImageSelected(String? imageId) => super.noSuchMethod(
    Invocation.method(#onImageSelected, [imageId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> getSingleImageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleImageSize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void searchAndReplace(String? search, String? replace) => super.noSuchMethod(
    Invocation.method(#searchAndReplace, [search, replace]),
    returnValueForMissingStub: null,
  );

  @override
  void countOccurrences(String? search) => super.noSuchMethod(
    Invocation.method(#countOccurrences, [search]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> updateCaption({required String? caption}) =>
      (super.noSuchMethod(
            Invocation.method(#updateCaption, [], {#caption: caption}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateImage({required _i5.AppImage? image}) =>
      (super.noSuchMethod(
            Invocation.method(#updateImage, [], {#image: image}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeImage(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [imageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, int> getAspectRatioCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAspectRatioCounts, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  int getTotalImagesSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalImagesSize, []),
            returnValue: 0,
          )
          as int);

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#updateSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCaseSensitive() => super.noSuchMethod(
    Invocation.method(#toggleCaseSensitive, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  double getAverageWordsPerCaption() =>
      (super.noSuchMethod(
            Invocation.method(#getAverageWordsPerCaption, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i6.Future<void> duplicateImage() =>
      (super.noSuchMethod(
            Invocation.method(#duplicateImage, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addCategory(String? name) => super.noSuchMethod(
    Invocation.method(#addCategory, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void removeCategory(String? name) => super.noSuchMethod(
    Invocation.method(#removeCategory, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void renameCategory(String? oldName, String? newName) => super.noSuchMethod(
    Invocation.method(#renameCategory, [oldName, newName]),
    returnValueForMissingStub: null,
  );

  @override
  void setActiveCategory(String? name) => super.noSuchMethod(
    Invocation.method(#setActiveCategory, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderCategories(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderCategories, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  void emit(_i2.ImageListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i7.Change<_i2.ImageListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [StructuredCaptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStructuredCaptionRepository extends _i1.Mock
    implements _i8.StructuredCaptionRepository {
  MockStructuredCaptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.IdeogramCaption> generateStructuredCaption(
    _i9.LlmConfig? config,
    _i10.File? imageFile, {
    required void Function(String)? onProgress,
    _i11.StructuredBatchOverrides? overrides,
    bool? debugMode = false,
    bool? disableSam = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateStructuredCaption,
              [config, imageFile],
              {
                #onProgress: onProgress,
                #overrides: overrides,
                #debugMode: debugMode,
                #disableSam: disableSam,
              },
            ),
            returnValue: _i6.Future<_i3.IdeogramCaption>.value(
              _FakeIdeogramCaption_1(
                this,
                Invocation.method(
                  #generateStructuredCaption,
                  [config, imageFile],
                  {
                    #onProgress: onProgress,
                    #overrides: overrides,
                    #debugMode: debugMode,
                    #disableSam: disableSam,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.IdeogramCaption>);

  @override
  _i4.VlmAnalysis parseAnalysisJson(Map<String, dynamic>? json) =>
      (super.noSuchMethod(
            Invocation.method(#parseAnalysisJson, [json]),
            returnValue: _FakeVlmAnalysis_2(
              this,
              Invocation.method(#parseAnalysisJson, [json]),
            ),
          )
          as _i4.VlmAnalysis);

  @override
  List<_i12.SamDetection> matchDetectionsToObjects(
    List<_i12.SamDetection>? detections,
    List<_i8.VlmObjectBboxPair>? vlmObjects,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#matchDetectionsToObjects, [
              detections,
              vlmObjects,
            ]),
            returnValue: <_i12.SamDetection>[],
          )
          as List<_i12.SamDetection>);

  @override
  _i3.IdeogramCaption buildIdeogramCaption(
    List<String>? globalPalette,
    _i4.VlmAnalysis? analysis,
    List<_i12.SamDetection>? detections,
    Map<int, List<String>>? elementPalettes,
    _i11.StructuredBatchOverrides? overrides,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildIdeogramCaption, [
              globalPalette,
              analysis,
              detections,
              elementPalettes,
              overrides,
            ]),
            returnValue: _FakeIdeogramCaption_1(
              this,
              Invocation.method(#buildIdeogramCaption, [
                globalPalette,
                analysis,
                detections,
                elementPalettes,
                overrides,
              ]),
            ),
          )
          as _i3.IdeogramCaption);

  @override
  bool isLikelyGroup(String? name, String? desc) =>
      (super.noSuchMethod(
            Invocation.method(#isLikelyGroup, [name, desc]),
            returnValue: false,
          )
          as bool);
}
