// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/features/structured_captioning/logic/structured_captioning_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;
import 'dart:io' as _i11;

import 'package:flutter_bloc/flutter_bloc.dart' as _i8;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:yofardev_captioner/features/image_list/data/models/app_image.dart'
    as _i5;
import 'package:yofardev_captioner/features/image_list/logic/image_list_cubit.dart'
    as _i2;
import 'package:yofardev_captioner/features/llm_config/data/models/llm_config.dart'
    as _i10;
import 'package:yofardev_captioner/features/llm_config/data/models/structured_batch_overrides.dart'
    as _i12;
import 'package:yofardev_captioner/features/structured_captioning/data/models/ideogram_caption.dart'
    as _i3;
import 'package:yofardev_captioner/features/structured_captioning/data/models/vlm_analysis.dart'
    as _i4;
import 'package:yofardev_captioner/features/structured_captioning/data/repositories/structured_caption_repository.dart'
    as _i9;
import 'package:yofardev_captioner/features/structured_captioning/data/services/sam_process_service.dart'
    as _i13;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeImageListState_0 extends _i1.SmartFake
    implements _i2.ImageListState {
  _FakeImageListState_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdeogramCaption_1 extends _i1.SmartFake
    implements _i3.IdeogramCaption {
  _FakeIdeogramCaption_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeIdeogramElement_2 extends _i1.SmartFake
    implements _i3.IdeogramElement {
  _FakeIdeogramElement_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVlmAnalysis_3 extends _i1.SmartFake implements _i4.VlmAnalysis {
  _FakeVlmAnalysis_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ImageListCubit].
///
/// See the documentation for Mockito's code generation for more information.
class MockImageListCubit extends _i1.Mock implements _i2.ImageListCubit {
  MockImageListCubit() {
    _i1.throwOnMissingStub(this);
  }

  @override
  List<_i5.AppImage> get filteredImages =>
      (super.noSuchMethod(
            Invocation.getter(#filteredImages),
            returnValue: <_i5.AppImage>[],
          )
          as List<_i5.AppImage>);

  @override
  List<_i5.AppImage> get displayedImages =>
      (super.noSuchMethod(
            Invocation.getter(#displayedImages),
            returnValue: <_i5.AppImage>[],
          )
          as List<_i5.AppImage>);

  @override
  _i2.ImageListState get state =>
      (super.noSuchMethod(
            Invocation.getter(#state),
            returnValue: _FakeImageListState_0(this, Invocation.getter(#state)),
          )
          as _i2.ImageListState);

  @override
  _i6.Stream<_i2.ImageListState> get stream =>
      (super.noSuchMethod(
            Invocation.getter(#stream),
            returnValue: _i6.Stream<_i2.ImageListState>.empty(),
          )
          as _i6.Stream<_i2.ImageListState>);

  @override
  bool get isClosed =>
      (super.noSuchMethod(Invocation.getter(#isClosed), returnValue: false)
          as bool);

  @override
  _i6.Future<void> onInit({String? folderPath}) =>
      (super.noSuchMethod(
            Invocation.method(#onInit, [], {#folderPath: folderPath}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onFolderPicked(String? folderPath, {bool? force = false}) =>
      (super.noSuchMethod(
            Invocation.method(#onFolderPicked, [folderPath], {#force: force}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> onFileOpened(String? filePath) =>
      (super.noSuchMethod(
            Invocation.method(#onFileOpened, [filePath]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void nextImage() => super.noSuchMethod(
    Invocation.method(#nextImage, []),
    returnValueForMissingStub: null,
  );

  @override
  void previousImage() => super.noSuchMethod(
    Invocation.method(#previousImage, []),
    returnValueForMissingStub: null,
  );

  @override
  void setGuidanceEnabled(bool? enabled) => super.noSuchMethod(
    Invocation.method(#setGuidanceEnabled, [enabled]),
    returnValueForMissingStub: null,
  );

  @override
  void setGuidance(String? imagePath, String? text) => super.noSuchMethod(
    Invocation.method(#setGuidance, [imagePath, text]),
    returnValueForMissingStub: null,
  );

  @override
  String guidanceFor(String? imagePath) =>
      (super.noSuchMethod(
            Invocation.method(#guidanceFor, [imagePath]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#guidanceFor, [imagePath]),
            ),
          )
          as String);

  @override
  _i6.Future<void> saveChanges() =>
      (super.noSuchMethod(
            Invocation.method(#saveChanges, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void onSortChanged(_i2.SortBy? sortBy, bool? sortAscending) =>
      super.noSuchMethod(
        Invocation.method(#onSortChanged, [sortBy, sortAscending]),
        returnValueForMissingStub: null,
      );

  @override
  void onImageSelected(String? imageId) => super.noSuchMethod(
    Invocation.method(#onImageSelected, [imageId]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> getSingleImageSize() =>
      (super.noSuchMethod(
            Invocation.method(#getSingleImageSize, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void searchAndReplace(String? search, String? replace) => super.noSuchMethod(
    Invocation.method(#searchAndReplace, [search, replace]),
    returnValueForMissingStub: null,
  );

  @override
  void countOccurrences(String? search) => super.noSuchMethod(
    Invocation.method(#countOccurrences, [search]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> updateCaption({required String? caption}) =>
      (super.noSuchMethod(
            Invocation.method(#updateCaption, [], {#caption: caption}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> updateImage({required _i5.AppImage? image}) =>
      (super.noSuchMethod(
            Invocation.method(#updateImage, [], {#image: image}),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Set<String> getAllUniqueTags() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUniqueTags, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  Set<String> getAllUniqueMediums() =>
      (super.noSuchMethod(
            Invocation.method(#getAllUniqueMediums, []),
            returnValue: <String>{},
          )
          as Set<String>);

  @override
  _i6.Future<void> removeImage(String? imageId) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [imageId]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> writeCaptionFiles() =>
      (super.noSuchMethod(
            Invocation.method(#writeCaptionFiles, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeCaptionFiles() =>
      (super.noSuchMethod(
            Invocation.method(#removeCaptionFiles, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  Map<String, int> getAspectRatioCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getAspectRatioCounts, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  Map<String, int> getTagCounts() =>
      (super.noSuchMethod(
            Invocation.method(#getTagCounts, []),
            returnValue: <String, int>{},
          )
          as Map<String, int>);

  @override
  int getTotalImagesSize() =>
      (super.noSuchMethod(
            Invocation.method(#getTotalImagesSize, []),
            returnValue: 0,
          )
          as int);

  @override
  void updateSearchQuery(String? query) => super.noSuchMethod(
    Invocation.method(#updateSearchQuery, [query]),
    returnValueForMissingStub: null,
  );

  @override
  void toggleCaseSensitive() => super.noSuchMethod(
    Invocation.method(#toggleCaseSensitive, []),
    returnValueForMissingStub: null,
  );

  @override
  void clearSearch() => super.noSuchMethod(
    Invocation.method(#clearSearch, []),
    returnValueForMissingStub: null,
  );

  @override
  double getAverageWordsPerCaption() =>
      (super.noSuchMethod(
            Invocation.method(#getAverageWordsPerCaption, []),
            returnValue: 0.0,
          )
          as double);

  @override
  _i6.Future<void> duplicateImage() =>
      (super.noSuchMethod(
            Invocation.method(#duplicateImage, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void addCategory(String? name, {String? format = 'txt'}) =>
      super.noSuchMethod(
        Invocation.method(#addCategory, [name], {#format: format}),
        returnValueForMissingStub: null,
      );

  @override
  void removeCategory(String? name) => super.noSuchMethod(
    Invocation.method(#removeCategory, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void renameCategory(String? oldName, String? newName) => super.noSuchMethod(
    Invocation.method(#renameCategory, [oldName, newName]),
    returnValueForMissingStub: null,
  );

  @override
  void setActiveCategory(String? name) => super.noSuchMethod(
    Invocation.method(#setActiveCategory, [name]),
    returnValueForMissingStub: null,
  );

  @override
  void reorderCategories(int? oldIndex, int? newIndex) => super.noSuchMethod(
    Invocation.method(#reorderCategories, [oldIndex, newIndex]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> addTag(String? rawTag) =>
      (super.noSuchMethod(
            Invocation.method(#addTag, [rawTag]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> removeTag(String? tag) =>
      (super.noSuchMethod(
            Invocation.method(#removeTag, [tag]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  _i6.Future<void> setTags(List<String>? rawTags) =>
      (super.noSuchMethod(
            Invocation.method(#setTags, [rawTags]),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);

  @override
  void emit(_i2.ImageListState? state) => super.noSuchMethod(
    Invocation.method(#emit, [state]),
    returnValueForMissingStub: null,
  );

  @override
  void onChange(_i8.Change<_i2.ImageListState>? change) => super.noSuchMethod(
    Invocation.method(#onChange, [change]),
    returnValueForMissingStub: null,
  );

  @override
  void addError(Object? error, [StackTrace? stackTrace]) => super.noSuchMethod(
    Invocation.method(#addError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  void onError(Object? error, StackTrace? stackTrace) => super.noSuchMethod(
    Invocation.method(#onError, [error, stackTrace]),
    returnValueForMissingStub: null,
  );

  @override
  _i6.Future<void> close() =>
      (super.noSuchMethod(
            Invocation.method(#close, []),
            returnValue: _i6.Future<void>.value(),
            returnValueForMissingStub: _i6.Future<void>.value(),
          )
          as _i6.Future<void>);
}

/// A class which mocks [StructuredCaptionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockStructuredCaptionRepository extends _i1.Mock
    implements _i9.StructuredCaptionRepository {
  MockStructuredCaptionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i3.IdeogramCaption> generateStructuredCaption(
    _i10.LlmConfig? config,
    _i11.File? imageFile, {
    required void Function(String)? onProgress,
    _i12.StructuredBatchOverrides? overrides,
    bool? debugMode = false,
    bool? disableSam = false,
    bool? vlmEmitsXyxy = true,
    String? guidance = '',
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #generateStructuredCaption,
              [config, imageFile],
              {
                #onProgress: onProgress,
                #overrides: overrides,
                #debugMode: debugMode,
                #disableSam: disableSam,
                #vlmEmitsXyxy: vlmEmitsXyxy,
                #guidance: guidance,
              },
            ),
            returnValue: _i6.Future<_i3.IdeogramCaption>.value(
              _FakeIdeogramCaption_1(
                this,
                Invocation.method(
                  #generateStructuredCaption,
                  [config, imageFile],
                  {
                    #onProgress: onProgress,
                    #overrides: overrides,
                    #debugMode: debugMode,
                    #disableSam: disableSam,
                    #vlmEmitsXyxy: vlmEmitsXyxy,
                    #guidance: guidance,
                  },
                ),
              ),
            ),
          )
          as _i6.Future<_i3.IdeogramCaption>);

  @override
  _i6.Future<Map<int, List<int>>> computeSamBboxes({
    required _i11.File? imageFile,
    required _i3.IdeogramCaption? caption,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#computeSamBboxes, [], {
              #imageFile: imageFile,
              #caption: caption,
            }),
            returnValue: _i6.Future<Map<int, List<int>>>.value(
              <int, List<int>>{},
            ),
          )
          as _i6.Future<Map<int, List<int>>>);

  @override
  _i6.Future<_i3.IdeogramElement> recaptionElement({
    required _i10.LlmConfig? config,
    required _i11.File? imageFile,
    required _i3.IdeogramCaption? currentCaption,
    required int? elementIndex,
    String? instructions,
    bool? cropToBbox = false,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#recaptionElement, [], {
              #config: config,
              #imageFile: imageFile,
              #currentCaption: currentCaption,
              #elementIndex: elementIndex,
              #instructions: instructions,
              #cropToBbox: cropToBbox,
            }),
            returnValue: _i6.Future<_i3.IdeogramElement>.value(
              _FakeIdeogramElement_2(
                this,
                Invocation.method(#recaptionElement, [], {
                  #config: config,
                  #imageFile: imageFile,
                  #currentCaption: currentCaption,
                  #elementIndex: elementIndex,
                  #instructions: instructions,
                  #cropToBbox: cropToBbox,
                }),
              ),
            ),
          )
          as _i6.Future<_i3.IdeogramElement>);

  @override
  String computeAspectRatio(int? width, int? height) =>
      (super.noSuchMethod(
            Invocation.method(#computeAspectRatio, [width, height]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#computeAspectRatio, [width, height]),
            ),
          )
          as String);

  @override
  String? extractJsonObject(String? raw) =>
      (super.noSuchMethod(Invocation.method(#extractJsonObject, [raw]))
          as String?);

  @override
  List<int>? normalizeBbox(dynamic raw, {bool? vlmEmitsXyxy = true}) =>
      (super.noSuchMethod(
            Invocation.method(
              #normalizeBbox,
              [raw],
              {#vlmEmitsXyxy: vlmEmitsXyxy},
            ),
          )
          as List<int>?);

  @override
  _i4.VlmAnalysis parseAnalysisJson(
    Map<String, dynamic>? json, {
    bool? vlmEmitsXyxy = true,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #parseAnalysisJson,
              [json],
              {#vlmEmitsXyxy: vlmEmitsXyxy},
            ),
            returnValue: _FakeVlmAnalysis_3(
              this,
              Invocation.method(
                #parseAnalysisJson,
                [json],
                {#vlmEmitsXyxy: vlmEmitsXyxy},
              ),
            ),
          )
          as _i4.VlmAnalysis);

  @override
  List<_i13.SamDetection> matchDetectionsToObjects(
    List<_i13.SamDetection>? detections,
    List<_i9.VlmObjectBboxPair>? vlmObjects,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#matchDetectionsToObjects, [
              detections,
              vlmObjects,
            ]),
            returnValue: <_i13.SamDetection>[],
          )
          as List<_i13.SamDetection>);

  @override
  _i3.IdeogramCaption buildIdeogramCaption(
    List<String>? globalPalette,
    _i4.VlmAnalysis? analysis,
    List<_i13.SamDetection>? detections,
    Map<int, List<String>>? elementPalettes,
    _i12.StructuredBatchOverrides? overrides,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#buildIdeogramCaption, [
              globalPalette,
              analysis,
              detections,
              elementPalettes,
              overrides,
            ]),
            returnValue: _FakeIdeogramCaption_1(
              this,
              Invocation.method(#buildIdeogramCaption, [
                globalPalette,
                analysis,
                detections,
                elementPalettes,
                overrides,
              ]),
            ),
          )
          as _i3.IdeogramCaption);

  @override
  bool isLikelyGroup(String? name, String? desc) =>
      (super.noSuchMethod(
            Invocation.method(#isLikelyGroup, [name, desc]),
            returnValue: false,
          )
          as bool);

  @override
  double computeIou(List<int>? a, List<int>? b) =>
      (super.noSuchMethod(
            Invocation.method(#computeIou, [a, b]),
            returnValue: 0.0,
          )
          as double);
}
