// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/logic/images_list/image_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yofardev_captioner/models/caption_database.dart' as _i2;
import 'package:yofardev_captioner/utils/app_file_utils.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeCaptionDatabase_0 extends _i1.SmartFake
    implements _i2.CaptionDatabase {
  _FakeCaptionDatabase_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AppFileUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFileUtils extends _i1.Mock implements _i3.AppFileUtils {
  MockAppFileUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<dynamic>> onFolderPicked(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#onFolderPicked, [folderPath]),
            returnValue: _i4.Future<List<dynamic>>.value(<dynamic>[]),
          )
          as _i4.Future<List<dynamic>>);

  @override
  _i4.Future<_i2.CaptionDatabase> readDb(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#readDb, [folderPath]),
            returnValue: _i4.Future<_i2.CaptionDatabase>.value(
              _FakeCaptionDatabase_0(
                this,
                Invocation.method(#readDb, [folderPath]),
              ),
            ),
          )
          as _i4.Future<_i2.CaptionDatabase>);

  @override
  _i4.Future<void> writeDb(String? folderPath, _i2.CaptionDatabase? db) =>
      (super.noSuchMethod(
            Invocation.method(#writeDb, [folderPath, db]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updateDbForRename(
    Map<String, String>? oldNameToNewName,
    String? folderPath,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateDbForRename, [
              oldNameToNewName,
              folderPath,
            ]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> exportAsArchive(String? folderPath, List<dynamic>? images) =>
      (super.noSuchMethod(
            Invocation.method(#exportAsArchive, [folderPath, images]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeImage(_i5.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#removeImage, [imageFile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> saveCaptionToFile(dynamic image) =>
      (super.noSuchMethod(
            Invocation.method(#saveCaptionToFile, [image]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  int compareNatural(String? a, String? b) =>
      (super.noSuchMethod(
            Invocation.method(#compareNatural, [a, b]),
            returnValue: 0,
          )
          as int);
}
