// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/features/captioning/data/repositories/caption_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;
import 'package:yofardev_captioner/features/captioning/data/services/caption_service.dart'
    as _i2;
import 'package:yofardev_captioner/features/llm_config/data/models/llm_config.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CaptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaptionService extends _i1.Mock implements _i2.CaptionService {
  MockCaptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getCaption(
    _i4.LlmConfig? config,
    _i5.File? image,
    String? prompt,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getCaption, [config, image, prompt]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#getCaption, [config, image, prompt]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> rewriteCaption(
    _i4.LlmConfig? config,
    String? currentCaption,
    String? instructions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rewriteCaption, [
              config,
              currentCaption,
              instructions,
            ]),
            returnValue: _i3.Future<String>.value(
              _i6.dummyValue<String>(
                this,
                Invocation.method(#rewriteCaption, [
                  config,
                  currentCaption,
                  instructions,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String buildUrl(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#buildUrl, [baseUrl]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#buildUrl, [baseUrl]),
            ),
          )
          as String);
}
