// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/features/structured_captioning/data/repositories/structured_caption_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;
import 'dart:io' as _i5;

import 'package:image/image.dart' as _i12;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;
import 'package:yofardev_captioner/core/utils/cancel_token.dart' as _i6;
import 'package:yofardev_captioner/features/captioning/data/services/caption_service.dart'
    as _i2;
import 'package:yofardev_captioner/features/llm_config/data/models/llm_config.dart'
    as _i4;
import 'package:yofardev_captioner/features/structured_captioning/data/services/bbox_highlight_service.dart'
    as _i8;
import 'package:yofardev_captioner/features/structured_captioning/data/services/color_extraction_service.dart'
    as _i11;
import 'package:yofardev_captioner/features/structured_captioning/data/services/sam_process_service.dart'
    as _i10;
import 'package:yofardev_captioner/features/structured_captioning/data/services/structured_prompt_loader.dart'
    as _i9;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [CaptionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCaptionService extends _i1.Mock implements _i2.CaptionService {
  MockCaptionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> getCaption(
    _i4.LlmConfig? config,
    _i5.File? image,
    String? prompt, {
    int? maxTokens,
    _i6.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getCaption,
              [config, image, prompt],
              {#maxTokens: maxTokens, #cancelToken: cancelToken},
            ),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #getCaption,
                  [config, image, prompt],
                  {#maxTokens: maxTokens, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> rewriteCaption(
    _i4.LlmConfig? config,
    String? currentCaption,
    String? instructions,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#rewriteCaption, [
              config,
              currentCaption,
              instructions,
            ]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#rewriteCaption, [
                  config,
                  currentCaption,
                  instructions,
                ]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> repairJson(
    _i4.LlmConfig? config,
    String? brokenOutput, {
    int? maxTokens,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #repairJson,
              [config, brokenOutput],
              {#maxTokens: maxTokens},
            ),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(
                  #repairJson,
                  [config, brokenOutput],
                  {#maxTokens: maxTokens},
                ),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  String buildUrl(String? baseUrl) =>
      (super.noSuchMethod(
            Invocation.method(#buildUrl, [baseUrl]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#buildUrl, [baseUrl]),
            ),
          )
          as String);
}

/// A class which mocks [BboxHighlightService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBboxHighlightService extends _i1.Mock
    implements _i8.BboxHighlightService {
  MockBboxHighlightService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> renderHighlightedJpeg(
    _i5.File? imageFile,
    List<int>? bbox,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#renderHighlightedJpeg, [imageFile, bbox]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#renderHighlightedJpeg, [imageFile, bbox]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> renderCroppedJpeg(_i5.File? imageFile, List<int>? bbox) =>
      (super.noSuchMethod(
            Invocation.method(#renderCroppedJpeg, [imageFile, bbox]),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#renderCroppedJpeg, [imageFile, bbox]),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<void> cleanup(String? path) =>
      (super.noSuchMethod(
            Invocation.method(#cleanup, [path]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}

/// A class which mocks [StructuredPromptLoader].
///
/// See the documentation for Mockito's code generation for more information.
class MockStructuredPromptLoader extends _i1.Mock
    implements _i9.StructuredPromptLoader {
  MockStructuredPromptLoader() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<String> loadVisionAnalysisPrompt() =>
      (super.noSuchMethod(
            Invocation.method(#loadVisionAnalysisPrompt, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#loadVisionAnalysisPrompt, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<String> loadElementRecaptionPrompt() =>
      (super.noSuchMethod(
            Invocation.method(#loadElementRecaptionPrompt, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#loadElementRecaptionPrompt, []),
              ),
            ),
          )
          as _i3.Future<String>);
}

/// A class which mocks [SamProcessService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSamProcessService extends _i1.Mock implements _i10.SamProcessService {
  MockSamProcessService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set scriptPathOverride(String? value) => super.noSuchMethod(
    Invocation.setter(#scriptPathOverride, value),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<String> findSamPythonForTest() =>
      (super.noSuchMethod(
            Invocation.method(#findSamPythonForTest, []),
            returnValue: _i3.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#findSamPythonForTest, []),
              ),
            ),
          )
          as _i3.Future<String>);

  @override
  _i3.Future<List<_i10.SamDetection>> detectObjects(
    String? imagePath,
    List<String>? objectNames, {
    List<List<int>?>? vlmBboxes,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #detectObjects,
              [imagePath, objectNames],
              {#vlmBboxes: vlmBboxes},
            ),
            returnValue: _i3.Future<List<_i10.SamDetection>>.value(
              <_i10.SamDetection>[],
            ),
          )
          as _i3.Future<List<_i10.SamDetection>>);
}

/// A class which mocks [ColorExtractionService].
///
/// See the documentation for Mockito's code generation for more information.
class MockColorExtractionService extends _i1.Mock
    implements _i11.ColorExtractionService {
  MockColorExtractionService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<String>> extractPalette(
    _i5.File? imageFile, {
    int? colorCount = 6,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extractPalette,
              [imageFile],
              {#colorCount: colorCount},
            ),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  _i3.Future<List<String>> extractPaletteFromRegion(
    _i5.File? imageFile,
    List<int>? bbox, {
    int? colorCount = 5,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #extractPaletteFromRegion,
              [imageFile, bbox],
              {#colorCount: colorCount},
            ),
            returnValue: _i3.Future<List<String>>.value(<String>[]),
          )
          as _i3.Future<List<String>>);

  @override
  String hexAt(_i12.Image? image, int? x, int? y) =>
      (super.noSuchMethod(
            Invocation.method(#hexAt, [image, x, y]),
            returnValue: _i7.dummyValue<String>(
              this,
              Invocation.method(#hexAt, [image, x, y]),
            ),
          )
          as String);
}
