// Mocks generated by Mockito 5.4.6 from annotations
// in yofardev_captioner/test/helpers/image_operations_helper_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:yofardev_captioner/models/app_image.dart' as _i4;
import 'package:yofardev_captioner/utils/app_file_utils.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AppFileUtils].
///
/// See the documentation for Mockito's code generation for more information.
class MockAppFileUtils extends _i1.Mock implements _i2.AppFileUtils {
  MockAppFileUtils() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> renameFilesToNumbers(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#renameFilesToNumbers, [folderPath]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  List<_i4.AppImage> sortAppImages(List<_i4.AppImage>? images) =>
      (super.noSuchMethod(
            Invocation.method(#sortAppImages, [images]),
            returnValue: <_i4.AppImage>[],
          )
          as List<_i4.AppImage>);

  @override
  int compareNatural(String? a, String? b) =>
      (super.noSuchMethod(
            Invocation.method(#compareNatural, [a, b]),
            returnValue: 0,
          )
          as int);

  @override
  _i3.Future<List<_i4.AppImage>> onFolderPicked(String? folderPath) =>
      (super.noSuchMethod(
            Invocation.method(#onFolderPicked, [folderPath]),
            returnValue: _i3.Future<List<_i4.AppImage>>.value(<_i4.AppImage>[]),
          )
          as _i3.Future<List<_i4.AppImage>>);

  @override
  _i3.Future<void> exportAsArchive(
    String? folderPath,
    List<_i4.AppImage>? images,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#exportAsArchive, [folderPath, images]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void removeImage(_i4.AppImage? image) => super.noSuchMethod(
    Invocation.method(#removeImage, [image]),
    returnValueForMissingStub: null,
  );
}
